[workspace]
authors = ["Vecko <36369090+VeckoTheGecko@users.noreply.github.com>"]
channels = ["conda-forge"]
name = "test-project"
platforms = ["osx-arm64"]
version = "0.1.0"

[tasks]

[dependencies]
pandas = ">=3.0.1,<4"
